[[hizmetler]]
  name = "Danışmanlık"
  weight = 10
  identifier = "danismanlik"
  url = "/hizmetler/danismanlik/"

[[hizmetler]]
  name = "Belgelendirme"
  weight = 20
  identifier = "belgelendirme"
  url = "/hizmetler/danismanlik/belgelendirme"

[[hizmetler]]
  name = "İlaçlama"
  weight = 60
  identifier = "ilaclama"
  url = "/hizmetler/ilaclama/"

[[main]]
  name = "Hizmetler"
  url = "/hizmetler/danismanlik/karadeniz-danismanlik/"
  weight = 10

[[main]]
  name = "Hakkımızda"
  url = "/hakkimizda/"
  weight = 20

[[main]]
  name = "İletişim"
  url = "/iletisim/"
  weight = 30

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/grup_karadeniz"
  weight = 10

[[social]]
  name = "Instagram"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 256 256\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-instagram\"><path d=\"M128,84a44,44,0,1,0,44,44A44.04978,44.04978,0,0,0,128,84Zm0,80a36,36,0,1,1,36-36A36.04061,36.04061,0,0,1,128,164ZM172,32H84A52.059,52.059,0,0,0,32,84v88a52.059,52.059,0,0,0,52,52h88a52.059,52.059,0,0,0,52-52V84A52.059,52.059,0,0,0,172,32Zm44,140a44.04978,44.04978,0,0,1-44,44H84a44.04978,44.04978,0,0,1-44-44V84A44.04978,44.04978,0,0,1,84,40h88a44.04978,44.04978,0,0,1,44,44ZM188,76a8,8,0,1,1-8-8A8.00917,8.00917,0,0,1,188,76Z\"></path></svg>"
  url = "https://www.instagram.com/karadenizgruprize"
  weight = 10
  
[[footer]]
  name = "Gizlilik Politikası"
  url = "/gizlilik-politikasi/"
  weight = 20
