[[hizmetler]]
  name = "Danışmanlık"
  weight = 10
  identifier = "danismanlik"
  url = "/hizmetler/danismanlik/"

[[hizmetler]]
  name = "Belgelendirme"
  weight = 20
  identifier = "belgelendirme"
  url = "/hizmetler/danismanlik/belgelendirme"

[[hizmetler]]
  name = "İlaçlama"
  weight = 60
  identifier = "ilaclama"
  url = "/hizmetler/ilaclama/"

[[main]]
  name = "Hizmetler"
  url = "/hizmetler/danismanlik/karadeniz-danismanlik/"
  weight = 10

[[main]]
  name = "Hakkımızda"
  url = "/hakkimizda/"
  weight = 20

[[main]]
  name = "İletişim"
  url = "/iletisim/"
  weight = 30

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/grup_karadeniz"
  weight = 10

[[social]]
  name = "Instagram"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-instagram\"><path d=\"M 8 3 C 5.243 3 3 5.243 3 8 L 3 16 C 3 18.757 5.243 21 8 21 L 16 21 C 18.757 21 21 18.757 21 16 L 21 8 C 21 5.243 18.757 3 16 3 L 8 3 z M 8 5 L 16 5 C 17.654 5 19 6.346 19 8 L 19 16 C 19 17.654 17.654 19 16 19 L 8 19 C 6.346 19 5 17.654 5 16 L 5 8 C 5 6.346 6.346 5 8 5 z M 17 6 A 1 1 0 0 0 16 7 A 1 1 0 0 0 17 8 A 1 1 0 0 0 18 7 A 1 1 0 0 0 17 6 z M 12 7 C 9.243 7 7 9.243 7 12 C 7 14.757 9.243 17 12 17 C 14.757 17 17 14.757 17 12 C 17 9.243 14.757 7 12 7 z M 12 9 C 13.654 9 15 10.346 15 12 C 15 13.654 13.654 15 12 15 C 10.346 15 9 13.654 9 12 C 9 10.346 10.346 9 12 9 z\"></path></svg>"
  url = "https://www.instagram.com/karadenizgruprize"
  weight = 10
  
[[footer]]
  name = "Gizlilik Politikası"
  url = "/gizlilik-politikasi/"
  weight = 20
