# Meta Data for SEO

## Homepage
title = "Karadeniz Grup"
titleSeparator = "-"
titleAddition = "Danışmanlık"
description = "Karadeniz Grup Danışmanlık."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "henkverlinde"
twitterCreator = "henkverlinde"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "tr_TR"

## JSON-LD
schemaType = "Organization"
schemaLogo = "kdz-logo-40.png"
schemaTwitter = "https://twitter.com/henkverlinde"
schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/gohugotr/karadeniz-grup.com"
schemaSection = "hakkimizda"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Katkı sağlayanlar <a href=\"https://#/\">CyMe Yazılım</a> ve <a href=\"https://www.render.com/\">Render</a>"

# Alert
alert = false
alertText = "Karadeniz Grubu beğendiyseniz <a class=\"alert-link\" href=\"https://github.com/gohugotr/karadeniz-grup.com\">GitHub'da Yıldız verin</a>. Teşekkürler!</a>"

# Edit Page
hizmetlerRepo = "https://github.com/gohugotr/karadeniz-grup.com"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false

  # Arama yapılacak içerikler
[params]
  mainSections = ["hakkimizda", "hizmetler"] # Arama yapılacak içerikler
  mainbg = "https://picsum.photos/1280/300.webp"
